defaults: ../../distillation_math.yaml
distillation:
  num_prompts_per_step: 64
  max_num_steps: 20
  val_batch_size: 256
  val_period: 10
  max_val_samples: 256
loss_fn:
  kl_type: reverse
checkpointing:
  checkpoint_dir: checkpoints/distillation-qwen3-32b-to-4b-base-seqpack
policy:
  model_name: /p/project1/envcomp/yll/.cache/huggingface/hub/models--Qwen--Qwen3-4B/snapshots/1cfa9a7208912126459214e8b04321603b3df60c
  dtensor_cfg:
    context_parallel_size: 1
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: true
  make_sequence_length_divisible_by: 2
teacher:
  model_name: /p/project1/envcomp/yll/.cache/huggingface/hub/models--Qwen--Qwen3-32B/snapshots/9216db5781bf21249d130ec9da846c4624c16137
  dtensor_cfg:
    tensor_parallel_size: 8
    context_parallel_size: 1
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: true
  make_sequence_length_divisible_by: 2
logger:
  log_dir: logs/distillation-qwen3-32b-to-4b-base-seqpack
  wandb:
    project: nemo-rl
    name: distillation-qwen3-32b-to-4b-base-seqpack
cluster:
  num_nodes: 2
