defaults: ./distillation-qwen3-32b-to-4b-2n4g-fsdp2tp1-long.v1.yaml
teacher:
  model_name: /p/project1/envcomp/yll/.cache/huggingface/hub/models--Qwen--Qwen3-14B/snapshots/40c069824f4251a91eefaf281ebe4c544efd3e18
checkpointing:
  checkpoint_dir: checkpoints/distillation-qwen3-14b-to-4b-2n4g-fsdp2tp1-long
logger:
  log_dir: logs/distillation-qwen3-14b-to-4b-2n4g-fsdp2tp1-long
  wandb:
    name: distillation-qwen3-14b-to-4b-2n4g-fsdp2tp1-long
