defaults: ./distillation-qwen3-32b-to-4b-base-2n8g-fsdp2tp2-long.v1.yaml
policy:
  model_name: /p/project1/envcomp/yll/.cache/huggingface/hub/models--Qwen--Qwen3-4B/snapshots/1cfa9a7208912126459214e8b04321603b3df60c
  generation:
    vllm_cfg:
      tensor_parallel_size: 1
teacher:
  model_name: /p/project1/envcomp/yll/.cache/huggingface/hub/models--Qwen--Qwen3-32B/snapshots/9216db5781bf21249d130ec9da846c4624c16137
checkpointing:
  checkpoint_dir: checkpoints/distillation-qwen3-32b-to-4b-2n4g-fsdp2tp1-long
logger:
  log_dir: logs/distillation-qwen3-32b-to-4b-2n4g-fsdp2tp1-long
  wandb:
    name: distillation-qwen3-32b-to-4b-2n4g-fsdp2tp1-long
cluster:
  gpus_per_node: 4
