defaults: ./distillation-qwen3-32b-to-4b-3n4g-isolated.v1.yaml
distillation:
  num_prompts_per_step: 16
  max_num_steps: 20
  val_batch_size: 16
  val_period: 0
policy:
  train_global_batch_size: 16
  generation_batch_size: 16
teacher:
  model_name: /p/project1/envcomp/yll/.cache/huggingface/hub/models--Qwen--Qwen3-14B/snapshots/40c069824f4251a91eefaf281ebe4c544efd3e18
checkpointing:
  checkpoint_dir: checkpoints/distillation-qwen3-14b-to-4b-3n4g-isolated-smoke
logger:
  log_dir: logs/distillation-qwen3-14b-to-4b-3n4g-isolated-smoke
  wandb:
    name: distillation-qwen3-14b-to-4b-3n4g-isolated-smoke
